version: "3.5"
services:
  server:
    extends:
      file: docker-compose_base.yml
      service: server
    ports:
      - "5001:5000"
    volumes:
      - "./src:/var/app/ishop/src"
    depends_on:
      db:
        condition: service_healthy
    tty: true


  db:
    extends:
      file: docker-compose_base.yml
      service: db
    ports:
      - "5432:5432"
    healthcheck:

      test: [ "CMD", "pg_isready", "-q", "-d", "ishop_db", "-U", "ishop_admin" ]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - "./volumes/db:/var/lib/postgresql/data"
      - "./psql_backup/ishop_db.sql:/docker-entrypoint-initdb.d/ishop_db.sql"

networks:
  default: