version: "3.5"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
      network: default
  db:
    image: postgres:15-alpine3.18

    environment:
      POSTGRES_USER: "ishop_admin"
      POSTGRES_PASSWORD: "Password78"
      POSTGRES_DB: "ishop_db"

networks:
  default: