name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]
    
jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "16.171.64.215"
          REMOTE_USER: "root"
          TARGET: "/home/ishop_admin/projects/ishop"
